services:
  web:
    build: 
      context: .
    ports:
      - "8080:8080"
    networks:
      - spring-postgres
  postgresqldb:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=liuyi
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    expose:
      - 5432

  mongodb:


networks:
  spring-postgres:
volumes:
  db-data: