version: "3.9"
services:
  web:
    build: 
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: liuyi
    volume:
      postgres