spring:
    datasource:
        password: 123456
        url: jdbc:postgresql://localhost:5432/test
        username: liuyi
    jpa:
        hibernate:
            ddl-auto: none
            show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    sql:
        init:
            mode: always