spring:
    datasource:
        url: "jdbc:postgresql://db:5432/test"
        username: liuyi
        password: 123456
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: create
        